### ISSUE TITLE
crashes when running on attached data set

### ISSUE THREAD

**Issue by tischi** [cmci/MultiStackRegistration#4]
[MAX_Stack.zip](https://github.com/cmci/MultiStackRegistration/files/341617/MAX_Stack.zip)

![image](https://cloud.githubusercontent.com/assets/2157566/16491367/f26d2846-3edd-11e6-9564-d780297ec11a.png)

(Fiji Is Just) ImageJ 2.0.0-rc-49/1.51d; Java 1.8.0_66 [64-bit]; Windows 10 10.0; 51MB of 6022MB (<1%)

java.lang.ArrayIndexOutOfBoundsException: 1
    at de.embl.cmci.registration.MultiStackReg_.registerSlice(MultiStackReg_.java:2356)
    at de.embl.cmci.registration.MultiStackReg_.processDirectives(MultiStackReg_.java:571)
    at de.embl.cmci.registration.MultiStackReg_.core(MultiStackReg_.java:344)
    at de.embl.cmci.registration.MultiStackReg_.run(MultiStackReg_.java:252)
    at ij.IJ.runUserPlugIn(IJ.java:216)
    at ij.IJ.runPlugIn(IJ.java:180)
    at ij.Executer.runCommand(Executer.java:137)
    at ij.Executer.run(Executer.java:63)
    at java.lang.Thread.run(Thread.java:745)

**Comment by tischi** [comment]
The error does not occur when I choose "rigid body" instead of "affine"

**Comment by miura** [comment]
Hi @tischi 

here is the fix. 
https://github.com/cmci/MultiStackRegistration/releases/tag/v1.46.1
